name: build.yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Zulu OpenJDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Package
        run: mvn -B clean package

      - name: Create artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        run: chmod +x "./zztools/prepublish.sh" && ./zztools/prepublish.sh

      - name: Save dist in cache
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        uses: actions/cache@v4
        with:
          path: dist
          key: dist-${{ github.run_id }}

  publish-win:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    runs-on: ubuntu-22.04
    needs:
      - build
    env:
      FILE_NAME: "windows-${{ github.event_name == 'release' && github.event.release.name || github.sha }}.zip"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get from cache
        uses: actions/cache@v4
        with:
          path: dist
          key: dist-${{ github.run_id }}

      - name: Prepare windows artifacts
        run: chmod +x "./zztools/winpublish.sh" && ./zztools/winpublish.sh

      - name: Compact dist
        run: |
          cd "${{ github.workspace }}/dist" && zip -r "$FILE_NAME" .
          mv "${{ github.workspace }}/dist/$FILE_NAME" "${{ github.workspace }}/$FILE_NAME"

      - name: Upload artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.FILE_NAME }}"
          path: "${{ github.workspace }}/${{ env.FILE_NAME }}"

      - name: Attach into release
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE_TAG: "${{ github.ref_name }}"
        run: |
          gh release upload "$RELEASE_TAG" $FILE_NAME --repo $GITHUB_REPOSITORY --clobber

  publish-linux:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    runs-on: ubuntu-22.04
    needs:
      - build
    env:
      FILE_NAME: "linux-${{ github.event_name == 'release' && github.event.release.name || github.sha }}.tar.gz"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get from cache
        uses: actions/cache@v4
        with:
          path: dist
          key: dist-${{ github.run_id }}

      - name: Prepare windows artifacts
        run: chmod +x "./zztools/linuxpublish.sh" && ./zztools/linuxpublish.sh

      - name: Compact dist
        run: |
          tar -czvf "$FILE_NAME" -C "${{ github.workspace }}/dist" .

      - name: Upload artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.FILE_NAME }}"
          path: "${{ github.workspace }}/${{ env.FILE_NAME }}"

      - name: Attach into release
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE_TAG: "${{ github.ref_name }}"
        run: |
          gh release upload "$RELEASE_TAG" $FILE_NAME --repo $GITHUB_REPOSITORY --clobber
