name: build.yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Zulu OpenJDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Package
        run: mvn -B clean package

      - name: Create artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        run: chmod +x "./zztools/prepublish.sh" && ./zztools/prepublish.sh

      - name: Save dist in cache
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        uses: actions/cache@v4
        with:
          path: dist
          key: dist-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            dist-

  publish-win:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - build
    env:
      FILE_NAME: "windows-${{ github.event_name == 'release' && github.event.release.name || github.sha }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get from cache
        uses: actions/cache@v4
        with:
          path: dist
          key: dist-${{ runner.os }}-${{ github.sha }}

      - name: Prepare artifacts
        run: chmod +x "./zztools/winpublish.sh" && ./zztools/winpublish.sh

      - name: Create artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.FILE_NAME }}"
          path: "${{ github.workspace }}/dist"
          retention-days: 1

      - name: Upload to release
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ github.token }}
        run: |
          cd "${{ github.workspace }}/dist" && zip -r "${FILE_NAME}.zip" . && cd "${{ github.workspace }}"
          mv "${{ github.workspace }}/dist/${FILE_NAME}.zip" "${{ github.workspace }}/${FILE_NAME}.zip"
          gh release upload "${{ github.ref_name }}" "${FILE_NAME}.zip" --repo "${{ github.repository }}" --clobber

          sha256sum "${FILE_NAME}.zip" >> "${FILE_NAME}.zip.sha256"
          gh release upload "${{ github.ref_name }}" "${FILE_NAME}.zip.sha256" --repo "${{ github.repository }}" --clobber

          md5sum "${FILE_NAME}.zip" >> "${FILE_NAME}.zip.md5"
          gh release upload "${{ github.ref_name }}" "${FILE_NAME}.zip.md5" --repo "${{ github.repository }}" --clobber

  publish-linux:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - build
    env:
      FILE_NAME: "linux-${{ github.event_name == 'release' && github.event.release.name || github.sha }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get from cache
        uses: actions/cache@v4
        with:
          path: dist
          key: dist-${{ runner.os }}-${{ github.sha }}

      - name: Prepare artifacts
        run: chmod +x "./zztools/linuxpublish.sh" && ./zztools/linuxpublish.sh

      - name: Create artifacts
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.FILE_NAME }}"
          path: "${{ github.workspace }}/dist"
          retention-days: 1

      - name: Upload to release
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tar -czvf "${FILE_NAME}.tar.gz" -C "${{ github.workspace }}/dist" . && cd "${{ github.workspace }}"
          gh release upload "${{ github.ref_name }}" "${FILE_NAME}.tar.gz" --repo "${{ github.repository }}" --clobber

          sha256sum "${FILE_NAME}.tar.gz" >> "${FILE_NAME}.tar.gz.sha256"
          gh release upload "${{ github.ref_name }}" "${FILE_NAME}.tar.gz.sha256" --repo "${{ github.repository }}" --clobber

          md5sum "${FILE_NAME}.tar.gz" >> "${FILE_NAME}.tar.gz.md5"
          gh release upload "${{ github.ref_name }}" "${FILE_NAME}.tar.gz.md5" --repo "${{ github.repository }}" --clobber
